<a href="https://colab.research.google.com/github/boixee/ArewaDS-Deep_Learning_Pytorch/blob/main/week_1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arewa Data Science Academy


Deep Learning Cohort1.0


Name: Abubakar Labaran Salisu


Email: abubakarsalisulabaran@gmail.com


Exercises Solution

In [ ]:
import torch

2. Create a random tensor with shape (7, 7).

In [11]:
random_tensor_A = torch.rand(size=(7, 7))
random_tensor_A.shape

torch.Size([7, 7])

3.

In [12]:
random_tensor_B = torch.rand(size=(1, 7))

In [15]:
random_tensor_AB = torch.matmul(random_tensor_A, random_tensor_B.T)
random_tensor_AB, random_tensor_AB.shape

(tensor([[1.8370],
         [2.4211],
         [2.5836],
         [2.2988],
         [1.5997],
         [2.1766],
         [1.5780]]),
 torch.Size([7, 1]))

4.

In [16]:
torch.manual_seed(0)

In [17]:
random_tensor_A = torch.rand(size=(7, 7))
random_tensor_B = torch.rand(size=(1, 7))

random_tensor_AB = torch.matmul(random_tensor_A, random_tensor_B.T)

In [18]:
random_tensor_AB, random_tensor_AB.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5.

In [19]:
torch.cuda.manual_seed(73)

In [20]:
random_tensor_AB, random_tensor_AB.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

6.

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [23]:
tensor_1 = torch.rand(size=(2,3)).to(device)
tensor_2 = torch.rand(size=(2,3)).to(device)
tensor_1, tensor_2

(tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]], device='cuda:0'),
 tensor([[0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294]], device='cuda:0'))

7.

In [24]:
tensor_1 = torch.rand(size=(2,3)).to(device)
tensor_2 = torch.rand(size=(2,3)).to(device)

tensor_3 = torch.matmul(tensor_1, tensor_2.T)
tensor_3, tensor_3.shape


(tensor([[1.2478, 1.0013],
         [0.6995, 0.6665]], device='cuda:0'),
 torch.Size([2, 2]))

8.

In [26]:
max = torch.max(tensor_3)
min = torch.min(tensor_3)
max, min

(tensor(1.2478, device='cuda:0'), tensor(0.6665, device='cuda:0'))

9.

In [27]:
inx_max = torch.argmax(tensor_3)
inx_min = torch.argmin(tensor_3)
inx_max, inx_min

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

10.

In [28]:
torch.manual_seed(7)

In [29]:
newtensor_1 = torch.rand(size=(1, 1, 1, 10))

In [30]:
newtensor_1, newtensor_1.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))